require('opts')
require('keys')
require('plug')

require('autopairs-config')
require('lsp-config')
require('lualine-config')
require('nvim-cmp-config')
require('telescope-config')
require('treesitter-config')
require('nvim-tree-config')
require('toggleterm-config')
